create:
  directories: # Create directories for project
   - cmd
   - internal
   - internal/primary
   - internal/secondary
   - pkg
   - pkg/handler
   - pkg/models
   - pkg/repositories
  files: # Create files for project
   - ${resource}/default/main.tpl:cmd/main.go
resource: ./ # Absolute Path of templates



